spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/db_test
    username: testuser
    password: testuser12!@
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 30000

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2

  jackson:
    time-zone: Asia/Seoul

kakao:
  client:
    id: 00d421dfe436939847e9b29c63ea50ff
  redirect:
    url: http://localhost:8080/kakao/callback
  auth:
    uri: https://kauth.kakao.com
  api:
    uri: https://kapi.kakao.com

naver:
  client:
    id: F5RzgfzE8ER43MRwOClV
    secret: gP5FwjYxTo
  redirect:
    url: http://localhost:8080/naver/callback
  auth:
    uri: https://nid.naver.com
  api:
    uri: https://openapi.naver.com

apple:
  auth:
    uri: https://appleid.apple.com
  client:
    id: com.mediplussolution.hime.signin.apple
  team:
    id: 356H38265K
  login:
    key: 3JF847C2YR
  redirect:
    url: https://dev.hi-me.net/main-api/v1/auth/sns/apple/callback

server:
  tomcat:
    threads:
      min-spare: 10
      max: 200
