spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5454/db_test
#    username: testuser
#    password: testuser12!@
#    driver-class-name: org.postgresql.Driver
#
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 20
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      keepalive-time: 30000
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 1000
#      lettuce:
#        pool:
#          max-active: 16
#          max-idle: 8
#          min-idle: 2

  jackson:
    time-zone: Asia/Seoul

kakao:
  client:
#    id: 00d421dfe436939847e9b29c63ea50ff
    id: 2f7a0c460bb2fe8e7819b49eccaf3bde    #dev
  redirect:
    url: http://localhost:3000/login/callback/kakao
#    url: http://localhost:38080/main-api/v1/auth/sns/kakao/callback
#    url: https://dev.hi-me.net/main-api/v1/auth/sns/kakao/callback #dev
  auth:
    uri: https://kauth.kakao.com
  api:
    uri: https://kapi.kakao.com

naver:
  client:
    id: F5RzgfzE8ER43MRwOClV
#    id: dvqMjKV2DU166UeRyctA #dev
    secret: gP5FwjYxTo
#    secret: e88g7bl4XS       #dev
  redirect:
    url: http://localhost:8080/naver/callback
#    url: http://localhost:38080/main-api/v1/auth/sns/naver/callback
#    url: https://dev.hi-me.net/main-api/v1/auth/sns/naver/callback  #dev
  auth:
    uri: https://nid.naver.com
  api:
    uri: https://openapi.naver.com

apple:
  auth:
    uri: https://appleid.apple.com
  client:
    id: dev.hime.mediplussolution.com
  team:
    id: 356H38265K
  login:
    key: C26NZM477C
  redirect:
#    url: https://dev.hi-me.net/main-api/v1/auth/sns/apple/callback
    url: https://dev.hi-me.net/login/callback/apple

server:
  tomcat:
    threads:
      min-spare: 10
      max: 200
  port: 3000
